# Generated by Django 5.0 on 2025-09-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_phone',
            field=models.BooleanField(default=False),
        ),
    ]
