# Generated by Django 5.2.6 on 2025-11-22 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_profile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.profile')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.search')),
            ],
            options={
                'unique_together': {('search', 'profile')},
            },
        ),
    ]
